// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run DDL that the connection pooler can't handle — always use the
    // direct/unpooled URL here, never DATABASE_URL. See CLAUDE.md §3.
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
