// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 config: `prisma db seed` runs this command. (Not the legacy
    // package.json#prisma.seed field — that's the pre-7 convention.)
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run DDL that the connection pooler can't handle — always use the
    // direct/unpooled URL here, never DATABASE_URL. See CLAUDE.md §3.
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
